### ISSUE TITLE
Pulses for M314 too slow

### ISSUE THREAD

**Issue by urpwnd** [pplans/foundry-vtt-module-motion-tracker#43]
I fiddled with the in-game settings, and it's still too slow.

However, by editing the html config file: 

line 11, changing max="0.025" 

allowed me to get the pulse to occur about .7 seconds apart, which is (give or take) what the M314 does in the movie Aliens.

Could this be changed (or made to allow even shorter intervals if people like that)?

Thank you!

**Comment by pplans** [comment]
Hi! Yes this is quite easy to add, I'll do that for the version this morning

**Comment by pplans** [comment]
Maximum was raised to 0.1 in the latest version (0.5.8) :)
