### ISSUE TITLE
v9!

### ISSUE THREAD

**Issue by brunocalado** [pplans/foundry-vtt-module-motion-tracker#46]
Hi.

Please remove the foundry vtt warning.

Replace "compatibleCoreVersion":"0.9.0" by "compatibleCoreVersion":"9".

Docs: https://gitlab.com/foundrynet/foundryvtt/-/issues/5635

**Comment by pplans** [comment]
Hi Bruno! Yes sorry I was a bit off lately, the plus side is that it seems compatible, well, at least the basic functionalities :) I'll do that asap this morning

**Comment by brunocalado** [comment]
tks

**Comment by pplans** [comment]
I consider this issue closed :) don't hesitate to open it again if it does not work
