### ISSUE TITLE
V10 version?

### ISSUE THREAD

**Issue by jacksands** [pplans/foundry-vtt-module-motion-tracker#52]
Hi!  tks for your module! It is amazing!!!

next week Alien RPG will go V10, can you take a look if it is possible for motion tracker to upgrade to v10 too?

Anyway thank you very much for your effort, have been using your module forever!!!!

Erich
![motion](https://user-images.githubusercontent.com/7229143/197362936-db4d0595-e24e-4136-9271-59f95389d3f5.png)

**Comment by pplans** [comment]
Well current version is going to be v11 I'll close this ticket
