### ISSUE TITLE
Incompatiblility with v11

### ISSUE THREAD

**Issue by Txus5012** [pplans/foundry-vtt-module-motion-tracker#56]
Hi. Great module. Thanks!

In Foundry v11 doesn't seem to work, looks like an issue with the new PIXI.
![Error](https://github.com/pplans/foundry-vtt-module-motion-tracker/assets/87753744/773f00a9-39ea-4826-9495-fc725fd32ff1)

**Comment by r-valyar** [comment]
+1 to have this nice module updated to v11 if possible! :)

**Comment by azarius74** [comment]
+1

**Comment by messiahcide** [comment]
+1

**Comment by Melkkart** [comment]
+1

**Comment by Keladryel** [comment]
+1

**Comment by CodaBool** [comment]
@pplans do you plan on still maintaining this? I might have interest in forking if not.

**Comment by CodaBool** [comment]
have a working version. There are some console warnings about a sound file. I will try to resolve that but should be able to put out a PR to get this module fixed!

![image](https://github.com/pplans/foundry-vtt-module-motion-tracker/assets/61724833/36a9db7f-28ca-415d-89bd-b82e83953d7d)

**Comment by Bekradan** [comment]
Fabulous.  Well,done.


Kind regards,Wayne

On Friday, September 1, 2023, 7:29 pm, CodaBool ***@***.***> wrote:




have a working version. There are some console warnings about a sound file. I will try to resolve that but should be able to put out a PR to get this module fixed!

**Comment by pplans** [comment]
hi guys, yeah I plan to do so but have had troubles working on two parallel versions on my computer before and have no much time to digg it through. Am currently based on the stable version (10) until next release, you can make a PR I'll review it

**Comment by pplans** [comment]
Also, the sound file is an issue with the current state of the Foundry sound API which is kinda bad. I can't remember the details right now but it involved non cached memory for the sound boards, so each time you wanna play a sound it will try to load it. This process takes time and doesn't suit the sound for the motion tracker who needs high trigger precision

**Comment by CodaBool** [comment]
I have an implementation with AudioHelper, should have a PR out by end of today. We can discuss things once I have that made.

**Comment by CodaBool** [comment]
# [PR](https://github.com/pplans/foundry-vtt-module-motion-tracker/pull/58) 🐱

**Comment by pplans** [comment]
PR is being reviewed, sorry for the delays, been sick & still at work :')

**Comment by Mizy78** [comment]
How can I install a working v11 version?

**Comment by CodaBool** [comment]
best to just wait for the PR to get merged 

...but if you are feeling impatient the extra bug testing might be useful.

> commands written assuming you have git installed and `rm` 

1. install the v10 module
2. go to modules folder on your server for me this is `.../Data/modules/`
3. delete the motion_tracker folder
4. clone my fork `git clone https://github.com/CodaBool/motion_tracker.git`
5. make sure you have the module enabled and restart your server.
6. :sunglasses: should be using a v11 working version

if you run into any issues with the v11 version it'd be useful to know on that [pr](https://github.com/pplans/foundry-vtt-module-motion-tracker/pull/58) I opened.

**Comment by pplans** [comment]
Hi guys, the v11 migration should be online, thanks CodaBool for his efforts. Please let me know if we can close the issue

**Comment by rdefendi** [comment]
On a quick check the audio volume controls and the checkbox to ignore PCs don't seem to work. Other than that, it's great to have this module back!

**Comment by CodaBool** [comment]
Awesome, glad it's mostly working. I know why both those bugs are happening. Those should be straightforward fixes. I could probably put out a PR before the end of the month for those.

**Comment by pplans** [comment]
ok so am closing this issue then, we can make a second for the checkbox
