### ISSUE TITLE
Suggestion: Add an option to have tokens without any status be invisible to the tracker by default

### ISSUE THREAD

**Issue by ICronyI** [pplans/foundry-vtt-module-motion-tracker#57]
Basically, i would like to be able to tell the tracker to only track tokens who have a specific status icon, instead of having to put a status on all the tokens i don't want to be seen on the tracker

Thanks for reading!

**Comment by pplans** [comment]
Why not, I'll try to take a look, sorr for the delays

**Comment by ICronyI** [comment]
@pplans Thank you! is this still in the plans?

**Comment by pplans** [comment]
Hey, yeah, I don't work on it often but if it becomes pressing I do ^^ I'll do add this today, expect it arriving in the next days :)

**Comment by pplans** [comment]
Hello, I added an option that inverts the token statuses, so that if you flag as usual a token as immobile it will actually be mobile and vice-et-versa, please let me know how it goes for you with that feature

**Comment by ICronyI** [comment]
@pplans This does exactly what i wanted, thank you very much!

**Comment by pplans** [comment]
Lemme know if you have issues with it, I'll close the ticket :) glad I helped
