### ISSUE TITLE
Motion Tracker Not Visible 

### ISSUE THREAD

**Issue by Nyogtha68** [pplans/foundry-vtt-module-motion-tracker#68]
![image](https://github.com/pplans/foundry-vtt-module-motion-tracker/assets/88248539/843d8b47-50d0-45a5-bee4-4d1ab57f917a)
Motion tracker does not display properly (see image) or produce sounds when activated.

**Comment by pplans** [comment]
Can you please provide console warnings (F12), Foundry version as well as Motion tracker version ?

**Comment by Nyogtha68** [comment]
No matter. I found the issue. It was Theme: Glass module.  Thanks for the quick response though, and the awesome module.
