### ISSUE TITLE
Not seeing the button to launch this

### ISSUE THREAD

**Issue by codemonkey1972** [pplans/foundry-vtt-module-motion-tracker#75]
Using Foundry 11 build 315 with the Alien RPG 3.1.7.

I'm supposed to see the button to the top left of the chat window to launch this but I just see the D20 button.

I thought perhaps Dice Roller or Dice So Nice might be interfering, but disabled those and rebooted the server and I'm still not seeing it.

Any ideas?

**Comment by pplans** [comment]
Hi, yes!

The button has moved recently (motion tracker version 1.2.0, and the button from the chat was definitely removed on version 1.3.1). You can find the new button on the left of the scene with all the other buttons affecting the scene :
![image](https://github.com/pplans/foundry-vtt-module-motion-tracker/assets/1166855/dc28386f-6233-4213-8da2-b0d1b12b628f)
